
// This file has been generated by the GUI designer. Do not modify.
namespace DamageControl
{
	public partial class RegistroUsuario
	{
		private global::Gtk.Frame frameRegistro;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Alignment alignRegistro;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Image imgNuevoUsuario;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label labUsuarioRegistro;
		
		private global::Gtk.Entry entUsuarioRegistro;
		
		private global::Gtk.Button butBuscarUsuario;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label labContrasenaRegistro;
		
		private global::Gtk.Entry entContrasenaRegistro;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label labConfirmarContrasena;
		
		private global::Gtk.Entry entConfirmarContrasenaRegistro;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.Expander expCodigoAutorizacion;
		
		private global::Gtk.HBox hboxRegistro;
		
		private global::Gtk.Label labCodigoTipoUsuario;
		
		private global::Gtk.Entry entCodigoAutorizacion;
		
		private global::Gtk.Label GtkLabCodigoAutorizacion;
		
		private global::Gtk.Label GtkLabVacio;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button butCancelarReg;
		
		private global::Gtk.Button butLimpiarReg;
		
		private global::Gtk.Button butRegistrar;
		
		private global::Gtk.Label GtkLabRegistro;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DamageControl.RegistroUsuario
			this.Name = "DamageControl.RegistroUsuario";
			this.Title = global::Mono.Unix.Catalog.GetString ("Registro de Usuario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child DamageControl.RegistroUsuario.Gtk.Container+ContainerChild
			this.frameRegistro = new global::Gtk.Frame ();
			this.frameRegistro.Name = "frameRegistro";
			this.frameRegistro.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frameRegistro.BorderWidth = ((uint)(15));
			// Container child frameRegistro.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.alignRegistro = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignRegistro.Name = "alignRegistro";
			this.alignRegistro.BorderWidth = ((uint)(15));
			// Container child alignRegistro.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.imgNuevoUsuario = new global::Gtk.Image ();
			this.imgNuevoUsuario.Name = "imgNuevoUsuario";
			this.imgNuevoUsuario.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("DamageControl.imagenes.RegistrarUsuario.png");
			this.vbox3.Add (this.imgNuevoUsuario);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.imgNuevoUsuario]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labUsuarioRegistro = new global::Gtk.Label ();
			this.labUsuarioRegistro.WidthRequest = 170;
			this.labUsuarioRegistro.Name = "labUsuarioRegistro";
			this.labUsuarioRegistro.Xalign = 0F;
			this.labUsuarioRegistro.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Usuario: </b>");
			this.labUsuarioRegistro.UseMarkup = true;
			this.hbox5.Add (this.labUsuarioRegistro);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labUsuarioRegistro]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child hbox5.Gtk.Box+BoxChild
			this.entUsuarioRegistro = new global::Gtk.Entry ();
			this.entUsuarioRegistro.CanFocus = true;
			this.entUsuarioRegistro.Name = "entUsuarioRegistro";
			this.entUsuarioRegistro.IsEditable = true;
			this.entUsuarioRegistro.InvisibleChar = '•';
			this.hbox5.Add (this.entUsuarioRegistro);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entUsuarioRegistro]));
			w3.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butBuscarUsuario = new global::Gtk.Button ();
			this.butBuscarUsuario.WidthRequest = 40;
			this.butBuscarUsuario.HeightRequest = 35;
			this.butBuscarUsuario.CanFocus = true;
			this.butBuscarUsuario.Name = "butBuscarUsuario";
			this.butBuscarUsuario.UseUnderline = true;
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.butBuscarUsuario.Image = w4;
			this.hbox5.Add (this.butBuscarUsuario);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.butBuscarUsuario]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labContrasenaRegistro = new global::Gtk.Label ();
			this.labContrasenaRegistro.WidthRequest = 170;
			this.labContrasenaRegistro.Name = "labContrasenaRegistro";
			this.labContrasenaRegistro.Xalign = 0F;
			this.labContrasenaRegistro.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Contraseña: </b>");
			this.labContrasenaRegistro.UseMarkup = true;
			this.hbox6.Add (this.labContrasenaRegistro);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.labContrasenaRegistro]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(15));
			// Container child hbox6.Gtk.Box+BoxChild
			this.entContrasenaRegistro = new global::Gtk.Entry ();
			this.entContrasenaRegistro.Sensitive = false;
			this.entContrasenaRegistro.CanFocus = true;
			this.entContrasenaRegistro.Name = "entContrasenaRegistro";
			this.entContrasenaRegistro.IsEditable = true;
			this.entContrasenaRegistro.Visibility = false;
			this.entContrasenaRegistro.InvisibleChar = '•';
			this.hbox6.Add (this.entContrasenaRegistro);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entContrasenaRegistro]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labConfirmarContrasena = new global::Gtk.Label ();
			this.labConfirmarContrasena.WidthRequest = 170;
			this.labConfirmarContrasena.Name = "labConfirmarContrasena";
			this.labConfirmarContrasena.Xalign = 0F;
			this.labConfirmarContrasena.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Confirmar contraseña: </b>");
			this.labConfirmarContrasena.UseMarkup = true;
			this.hbox7.Add (this.labConfirmarContrasena);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labConfirmarContrasena]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(15));
			// Container child hbox7.Gtk.Box+BoxChild
			this.entConfirmarContrasenaRegistro = new global::Gtk.Entry ();
			this.entConfirmarContrasenaRegistro.Sensitive = false;
			this.entConfirmarContrasenaRegistro.CanFocus = true;
			this.entConfirmarContrasenaRegistro.Name = "entConfirmarContrasenaRegistro";
			this.entConfirmarContrasenaRegistro.IsEditable = true;
			this.entConfirmarContrasenaRegistro.Visibility = false;
			this.entConfirmarContrasenaRegistro.InvisibleChar = '•';
			this.hbox7.Add (this.entConfirmarContrasenaRegistro);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entConfirmarContrasenaRegistro]));
			w11.Position = 1;
			this.vbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame2.BorderWidth = ((uint)(15));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.expCodigoAutorizacion = new global::Gtk.Expander (null);
			this.expCodigoAutorizacion.CanFocus = true;
			this.expCodigoAutorizacion.Name = "expCodigoAutorizacion";
			this.expCodigoAutorizacion.Expanded = true;
			// Container child expCodigoAutorizacion.Gtk.Container+ContainerChild
			this.hboxRegistro = new global::Gtk.HBox ();
			this.hboxRegistro.Name = "hboxRegistro";
			this.hboxRegistro.Spacing = 6;
			this.hboxRegistro.BorderWidth = ((uint)(10));
			// Container child hboxRegistro.Gtk.Box+BoxChild
			this.labCodigoTipoUsuario = new global::Gtk.Label ();
			this.labCodigoTipoUsuario.WidthRequest = 170;
			this.labCodigoTipoUsuario.Name = "labCodigoTipoUsuario";
			this.labCodigoTipoUsuario.Xalign = 0F;
			this.labCodigoTipoUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Código de autorización: </b>");
			this.labCodigoTipoUsuario.UseMarkup = true;
			this.hboxRegistro.Add (this.labCodigoTipoUsuario);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxRegistro [this.labCodigoTipoUsuario]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(15));
			// Container child hboxRegistro.Gtk.Box+BoxChild
			this.entCodigoAutorizacion = new global::Gtk.Entry ();
			this.entCodigoAutorizacion.Sensitive = false;
			this.entCodigoAutorizacion.CanFocus = true;
			this.entCodigoAutorizacion.Name = "entCodigoAutorizacion";
			this.entCodigoAutorizacion.IsEditable = true;
			this.entCodigoAutorizacion.Visibility = false;
			this.entCodigoAutorizacion.InvisibleChar = '•';
			this.hboxRegistro.Add (this.entCodigoAutorizacion);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxRegistro [this.entCodigoAutorizacion]));
			w14.Position = 1;
			this.expCodigoAutorizacion.Add (this.hboxRegistro);
			this.GtkLabCodigoAutorizacion = new global::Gtk.Label ();
			this.GtkLabCodigoAutorizacion.Name = "GtkLabCodigoAutorizacion";
			this.GtkLabCodigoAutorizacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Falta algo");
			this.GtkLabCodigoAutorizacion.UseMarkup = true;
			this.GtkLabCodigoAutorizacion.UseUnderline = true;
			this.expCodigoAutorizacion.LabelWidget = this.GtkLabCodigoAutorizacion;
			this.GtkAlignment4.Add (this.expCodigoAutorizacion);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabVacio = new global::Gtk.Label ();
			this.GtkLabVacio.Name = "GtkLabVacio";
			this.GtkLabVacio.LabelProp = global::Mono.Unix.Catalog.GetString ("<b></b>");
			this.GtkLabVacio.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabVacio;
			this.vbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame2]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.butCancelarReg = new global::Gtk.Button ();
			this.butCancelarReg.WidthRequest = 150;
			this.butCancelarReg.HeightRequest = 50;
			this.butCancelarReg.CanFocus = true;
			this.butCancelarReg.Name = "butCancelarReg";
			this.butCancelarReg.UseUnderline = true;
			this.butCancelarReg.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox2.Add (this.butCancelarReg);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.butCancelarReg]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.butLimpiarReg = new global::Gtk.Button ();
			this.butLimpiarReg.WidthRequest = 150;
			this.butLimpiarReg.HeightRequest = 50;
			this.butLimpiarReg.CanFocus = true;
			this.butLimpiarReg.Name = "butLimpiarReg";
			this.butLimpiarReg.UseUnderline = true;
			this.butLimpiarReg.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox2.Add (this.butLimpiarReg);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.butLimpiarReg]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.butRegistrar = new global::Gtk.Button ();
			this.butRegistrar.WidthRequest = 150;
			this.butRegistrar.HeightRequest = 50;
			this.butRegistrar.CanFocus = true;
			this.butRegistrar.Name = "butRegistrar";
			this.butRegistrar.UseUnderline = true;
			this.butRegistrar.Label = global::Mono.Unix.Catalog.GetString ("Registrar");
			this.hbox2.Add (this.butRegistrar);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.butRegistrar]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			this.alignRegistro.Add (this.vbox3);
			this.GtkAlignment.Add (this.alignRegistro);
			this.frameRegistro.Add (this.GtkAlignment);
			this.GtkLabRegistro = new global::Gtk.Label ();
			this.GtkLabRegistro.Name = "GtkLabRegistro";
			this.GtkLabRegistro.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Registro de nuevo usuario</b>");
			this.GtkLabRegistro.UseMarkup = true;
			this.frameRegistro.LabelWidget = this.GtkLabRegistro;
			this.Add (this.frameRegistro);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 538;
			this.DefaultHeight = 450;
			this.Show ();
			this.butBuscarUsuario.Clicked += new global::System.EventHandler (this.OnButBuscarUsuarioClicked);
			this.expCodigoAutorizacion.Activated += new global::System.EventHandler (this.OnExpCodigoAutorizacionActivated);
			this.butCancelarReg.Clicked += new global::System.EventHandler (this.OnButCancelarRegClicked);
			this.butLimpiarReg.Clicked += new global::System.EventHandler (this.OnButLimpiarRegClicked);
			this.butRegistrar.Clicked += new global::System.EventHandler (this.OnButRegistrarClicked);
		}
	}
}
