
// This file has been generated by the GUI designer. Do not modify.
namespace DamageControl
{
	public partial class Calendario
	{
		private global::Gtk.Frame frameCalendario;
		
		private global::Gtk.Alignment GtkAligInterior;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Calendar calendar;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Button butCancelar;
		
		private global::Gtk.Button butAceptar;
		
		private global::Gtk.Label GtkLabCalendario;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DamageControl.Calendario
			this.Name = "DamageControl.Calendario";
			this.Title = global::Mono.Unix.Catalog.GetString ("Calendario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(15));
			// Container child DamageControl.Calendario.Gtk.Container+ContainerChild
			this.frameCalendario = new global::Gtk.Frame ();
			this.frameCalendario.Name = "frameCalendario";
			this.frameCalendario.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameCalendario.Gtk.Container+ContainerChild
			this.GtkAligInterior = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAligInterior.Name = "GtkAligInterior";
			this.GtkAligInterior.LeftPadding = ((uint)(12));
			this.GtkAligInterior.BorderWidth = ((uint)(15));
			// Container child GtkAligInterior.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.calendar = new global::Gtk.Calendar ();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(43));
			this.calendar.ShowWeekNumbers = true;
			this.vbox2.Add (this.calendar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.calendar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.butCancelar = new global::Gtk.Button ();
			this.butCancelar.WidthRequest = 50;
			this.butCancelar.HeightRequest = 50;
			this.butCancelar.CanFocus = true;
			this.butCancelar.Name = "butCancelar";
			this.butCancelar.UseUnderline = true;
			this.butCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox12.Add (this.butCancelar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.butCancelar]));
			w2.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.butAceptar = new global::Gtk.Button ();
			this.butAceptar.CanFocus = true;
			this.butAceptar.Name = "butAceptar";
			this.butAceptar.UseUnderline = true;
			this.butAceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox12.Add (this.butAceptar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.butAceptar]));
			w3.Position = 1;
			this.vbox2.Add (this.hbox12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
			w4.Position = 1;
			this.GtkAligInterior.Add (this.vbox2);
			this.frameCalendario.Add (this.GtkAligInterior);
			this.GtkLabCalendario = new global::Gtk.Label ();
			this.GtkLabCalendario.Name = "GtkLabCalendario";
			this.GtkLabCalendario.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Calendario</b>");
			this.GtkLabCalendario.UseMarkup = true;
			this.frameCalendario.LabelWidget = this.GtkLabCalendario;
			this.Add (this.frameCalendario);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 357;
			this.DefaultHeight = 335;
			this.Show ();
			this.calendar.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCalendarDaySelectedDoubleClick);
			this.butCancelar.Clicked += new global::System.EventHandler (this.OnButCancelarClicked);
			this.butAceptar.Clicked += new global::System.EventHandler (this.OnButAceptarClicked);
		}
	}
}
