
// This file has been generated by the GUI designer. Do not modify.
namespace DamageControl
{
	public partial class Profesiones
	{
		private global::Gtk.Frame frameProfesion;
		
		private global::Gtk.Alignment GtkAligInterior;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label labCodigoInstructor;
		
		private global::Gtk.Entry entCodigoInstructor;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Fixed fixedEspacio1;
		
		private global::Gtk.Label labNombreInstructor;
		
		private global::Gtk.Entry entNombreInstructor;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Fixed fixedEspacio;
		
		private global::Gtk.Label labProfesión1;
		
		private global::Gtk.ComboBox cbboxProfesion1;
		
		private global::Gtk.Label labFechaTitulo;
		
		private global::Gtk.Entry entFechaTitulo1;
		
		private global::Gtk.Button butCalendarioTituloInstructor;
		
		private global::Gtk.Fixed fixedEspacio2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button butAgregarProfesion2;
		
		private global::Gtk.Label labProfesión2;
		
		private global::Gtk.ComboBox cbboxProfesion2;
		
		private global::Gtk.Label labFechaTitulo1;
		
		private global::Gtk.Entry entFechaTitulo2;
		
		private global::Gtk.Button butCalendarioTituloInstructor1;
		
		private global::Gtk.Button butEliminarProfesion2;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button butAgregarProfesion3;
		
		private global::Gtk.Label labProfesión3;
		
		private global::Gtk.ComboBox cbboxProfesion3;
		
		private global::Gtk.Label labFechaTitulo2;
		
		private global::Gtk.Entry entFechaTitulo3;
		
		private global::Gtk.Button butCalendarioTituloInstructor2;
		
		private global::Gtk.Button butEliminarProfesion3;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button butAgregarProfesion4;
		
		private global::Gtk.Label labProfesión4;
		
		private global::Gtk.ComboBox cbboxProfesion4;
		
		private global::Gtk.Label labFechaTitulo3;
		
		private global::Gtk.Entry entFechaTitulo4;
		
		private global::Gtk.Button butCalendarioTituloInstructor3;
		
		private global::Gtk.Button butEliminarProfesion4;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button butAgregarProfesion5;
		
		private global::Gtk.Label labProfesión5;
		
		private global::Gtk.ComboBox cbboxProfesion5;
		
		private global::Gtk.Label labFechaTitulo4;
		
		private global::Gtk.Entry entFechaTitulo5;
		
		private global::Gtk.Button butCalendarioTituloInstructor4;
		
		private global::Gtk.Button butEliminarProfesion5;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button butAgregarProfesion6;
		
		private global::Gtk.Label labProfesión6;
		
		private global::Gtk.ComboBox cbboxProfesion6;
		
		private global::Gtk.Label labFechaTitulo5;
		
		private global::Gtk.Entry entFechaTitulo6;
		
		private global::Gtk.Button butCalendarioTituloInstructor5;
		
		private global::Gtk.Button butEliminarProfesion6;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Button butAgregarProfesion7;
		
		private global::Gtk.Label labProfesión7;
		
		private global::Gtk.ComboBox cbboxProfesion7;
		
		private global::Gtk.Label labFechaTitulo6;
		
		private global::Gtk.Entry entFechaTitulo7;
		
		private global::Gtk.Button butCalendarioTituloInstructor6;
		
		private global::Gtk.Button butEliminarProfesion7;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Button butAgregarProfesion8;
		
		private global::Gtk.Label labProfesión8;
		
		private global::Gtk.ComboBox cbboxProfesion8;
		
		private global::Gtk.Label labFechaTitulo7;
		
		private global::Gtk.Entry entFechaTitulo8;
		
		private global::Gtk.Button butCalendarioTituloInstructor7;
		
		private global::Gtk.Button butEliminarProfesion8;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Button butCancelar;
		
		private global::Gtk.Button butAceptar;
		
		private global::Gtk.Label GtkLabProfesiones;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DamageControl.Profesiones
			this.Name = "DamageControl.Profesiones";
			this.Title = global::Mono.Unix.Catalog.GetString ("Profesiones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(15));
			// Container child DamageControl.Profesiones.Gtk.Container+ContainerChild
			this.frameProfesion = new global::Gtk.Frame ();
			this.frameProfesion.Name = "frameProfesion";
			this.frameProfesion.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameProfesion.Gtk.Container+ContainerChild
			this.GtkAligInterior = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAligInterior.Name = "GtkAligInterior";
			this.GtkAligInterior.LeftPadding = ((uint)(12));
			this.GtkAligInterior.BorderWidth = ((uint)(15));
			// Container child GtkAligInterior.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labCodigoInstructor = new global::Gtk.Label ();
			this.labCodigoInstructor.WidthRequest = 166;
			this.labCodigoInstructor.HeightRequest = 35;
			this.labCodigoInstructor.Name = "labCodigoInstructor";
			this.labCodigoInstructor.Xalign = 0F;
			this.labCodigoInstructor.LabelProp = global::Mono.Unix.Catalog.GetString ("Código del instructor: ");
			this.hbox1.Add (this.labCodigoInstructor);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labCodigoInstructor]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entCodigoInstructor = new global::Gtk.Entry ();
			this.entCodigoInstructor.WidthRequest = 100;
			this.entCodigoInstructor.CanFocus = true;
			this.entCodigoInstructor.Name = "entCodigoInstructor";
			this.entCodigoInstructor.IsEditable = true;
			this.entCodigoInstructor.InvisibleChar = '•';
			this.hbox1.Add (this.entCodigoInstructor);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entCodigoInstructor]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixedEspacio1 = new global::Gtk.Fixed ();
			this.fixedEspacio1.WidthRequest = 78;
			this.fixedEspacio1.Name = "fixedEspacio1";
			this.fixedEspacio1.HasWindow = false;
			this.hbox4.Add (this.fixedEspacio1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixedEspacio1]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labNombreInstructor = new global::Gtk.Label ();
			this.labNombreInstructor.WidthRequest = 166;
			this.labNombreInstructor.HeightRequest = 35;
			this.labNombreInstructor.Name = "labNombreInstructor";
			this.labNombreInstructor.Xalign = 0F;
			this.labNombreInstructor.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre del instructor: ");
			this.hbox4.Add (this.labNombreInstructor);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labNombreInstructor]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entNombreInstructor = new global::Gtk.Entry ();
			this.entNombreInstructor.WidthRequest = 260;
			this.entNombreInstructor.CanFocus = true;
			this.entNombreInstructor.Name = "entNombreInstructor";
			this.entNombreInstructor.IsEditable = true;
			this.entNombreInstructor.InvisibleChar = '•';
			this.hbox4.Add (this.entNombreInstructor);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entNombreInstructor]));
			w5.Position = 2;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w6.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixedEspacio = new global::Gtk.Fixed ();
			this.fixedEspacio.WidthRequest = 40;
			this.fixedEspacio.Name = "fixedEspacio";
			this.fixedEspacio.HasWindow = false;
			this.hbox2.Add (this.fixedEspacio);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixedEspacio]));
			w8.Position = 0;
			w8.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labProfesión1 = new global::Gtk.Label ();
			this.labProfesión1.WidthRequest = 100;
			this.labProfesión1.HeightRequest = 35;
			this.labProfesión1.Name = "labProfesión1";
			this.labProfesión1.Xalign = 0F;
			this.labProfesión1.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox2.Add (this.labProfesión1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labProfesión1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Padding = ((uint)(10));
			// Container child hbox2.Gtk.Box+BoxChild
			this.cbboxProfesion1 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion1.WidthRequest = 200;
			this.cbboxProfesion1.Name = "cbboxProfesion1";
			this.hbox2.Add (this.cbboxProfesion1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbboxProfesion1]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labFechaTitulo = new global::Gtk.Label ();
			this.labFechaTitulo.WidthRequest = 130;
			this.labFechaTitulo.HeightRequest = 35;
			this.labFechaTitulo.Name = "labFechaTitulo";
			this.labFechaTitulo.Xalign = 0F;
			this.labFechaTitulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox2.Add (this.labFechaTitulo);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labFechaTitulo]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Padding = ((uint)(10));
			// Container child hbox2.Gtk.Box+BoxChild
			this.entFechaTitulo1 = new global::Gtk.Entry ();
			this.entFechaTitulo1.WidthRequest = 175;
			this.entFechaTitulo1.CanFocus = true;
			this.entFechaTitulo1.Name = "entFechaTitulo1";
			this.entFechaTitulo1.IsEditable = false;
			this.entFechaTitulo1.InvisibleChar = '•';
			this.hbox2.Add (this.entFechaTitulo1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entFechaTitulo1]));
			w12.Position = 4;
			w12.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor.WidthRequest = 40;
			this.butCalendarioTituloInstructor.CanFocus = true;
			this.butCalendarioTituloInstructor.Name = "butCalendarioTituloInstructor";
			this.butCalendarioTituloInstructor.UseUnderline = true;
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor.Image = w13;
			this.hbox2.Add (this.butCalendarioTituloInstructor);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.butCalendarioTituloInstructor]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixedEspacio2 = new global::Gtk.Fixed ();
			this.fixedEspacio2.WidthRequest = 40;
			this.fixedEspacio2.Name = "fixedEspacio2";
			this.fixedEspacio2.HasWindow = false;
			this.hbox2.Add (this.fixedEspacio2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixedEspacio2]));
			w15.Position = 6;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.butAgregarProfesion2 = new global::Gtk.Button ();
			this.butAgregarProfesion2.WidthRequest = 40;
			this.butAgregarProfesion2.CanFocus = true;
			this.butAgregarProfesion2.Name = "butAgregarProfesion2";
			this.butAgregarProfesion2.UseUnderline = true;
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion2.Image = w17;
			this.hbox3.Add (this.butAgregarProfesion2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.butAgregarProfesion2]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labProfesión2 = new global::Gtk.Label ();
			this.labProfesión2.WidthRequest = 100;
			this.labProfesión2.HeightRequest = 35;
			this.labProfesión2.Sensitive = false;
			this.labProfesión2.Name = "labProfesión2";
			this.labProfesión2.Xalign = 0F;
			this.labProfesión2.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox3.Add (this.labProfesión2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labProfesión2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Padding = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.cbboxProfesion2 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion2.WidthRequest = 200;
			this.cbboxProfesion2.Sensitive = false;
			this.cbboxProfesion2.Name = "cbboxProfesion2";
			this.hbox3.Add (this.cbboxProfesion2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cbboxProfesion2]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labFechaTitulo1 = new global::Gtk.Label ();
			this.labFechaTitulo1.WidthRequest = 130;
			this.labFechaTitulo1.HeightRequest = 35;
			this.labFechaTitulo1.Sensitive = false;
			this.labFechaTitulo1.Name = "labFechaTitulo1";
			this.labFechaTitulo1.Xalign = 0F;
			this.labFechaTitulo1.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox3.Add (this.labFechaTitulo1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labFechaTitulo1]));
			w21.Position = 3;
			w21.Expand = false;
			w21.Padding = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.entFechaTitulo2 = new global::Gtk.Entry ();
			this.entFechaTitulo2.WidthRequest = 175;
			this.entFechaTitulo2.Sensitive = false;
			this.entFechaTitulo2.CanFocus = true;
			this.entFechaTitulo2.Name = "entFechaTitulo2";
			this.entFechaTitulo2.IsEditable = true;
			this.entFechaTitulo2.InvisibleChar = '•';
			this.hbox3.Add (this.entFechaTitulo2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entFechaTitulo2]));
			w22.Position = 4;
			w22.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor1 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor1.WidthRequest = 40;
			this.butCalendarioTituloInstructor1.Sensitive = false;
			this.butCalendarioTituloInstructor1.CanFocus = true;
			this.butCalendarioTituloInstructor1.Name = "butCalendarioTituloInstructor1";
			this.butCalendarioTituloInstructor1.UseUnderline = true;
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor1.Image = w23;
			this.hbox3.Add (this.butCalendarioTituloInstructor1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.butCalendarioTituloInstructor1]));
			w24.Position = 5;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.butEliminarProfesion2 = new global::Gtk.Button ();
			this.butEliminarProfesion2.WidthRequest = 40;
			this.butEliminarProfesion2.Sensitive = false;
			this.butEliminarProfesion2.CanFocus = true;
			this.butEliminarProfesion2.Name = "butEliminarProfesion2";
			this.butEliminarProfesion2.UseUnderline = true;
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion2.Image = w25;
			this.hbox3.Add (this.butEliminarProfesion2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.butEliminarProfesion2]));
			w26.Position = 6;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butAgregarProfesion3 = new global::Gtk.Button ();
			this.butAgregarProfesion3.WidthRequest = 40;
			this.butAgregarProfesion3.Sensitive = false;
			this.butAgregarProfesion3.CanFocus = true;
			this.butAgregarProfesion3.Name = "butAgregarProfesion3";
			this.butAgregarProfesion3.UseUnderline = true;
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion3.Image = w28;
			this.hbox5.Add (this.butAgregarProfesion3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.butAgregarProfesion3]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labProfesión3 = new global::Gtk.Label ();
			this.labProfesión3.WidthRequest = 100;
			this.labProfesión3.HeightRequest = 35;
			this.labProfesión3.Sensitive = false;
			this.labProfesión3.Name = "labProfesión3";
			this.labProfesión3.Xalign = 0F;
			this.labProfesión3.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox5.Add (this.labProfesión3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labProfesión3]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Padding = ((uint)(10));
			// Container child hbox5.Gtk.Box+BoxChild
			this.cbboxProfesion3 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion3.WidthRequest = 200;
			this.cbboxProfesion3.Sensitive = false;
			this.cbboxProfesion3.Name = "cbboxProfesion3";
			this.hbox5.Add (this.cbboxProfesion3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cbboxProfesion3]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labFechaTitulo2 = new global::Gtk.Label ();
			this.labFechaTitulo2.WidthRequest = 130;
			this.labFechaTitulo2.HeightRequest = 35;
			this.labFechaTitulo2.Sensitive = false;
			this.labFechaTitulo2.Name = "labFechaTitulo2";
			this.labFechaTitulo2.Xalign = 0F;
			this.labFechaTitulo2.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox5.Add (this.labFechaTitulo2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labFechaTitulo2]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Padding = ((uint)(10));
			// Container child hbox5.Gtk.Box+BoxChild
			this.entFechaTitulo3 = new global::Gtk.Entry ();
			this.entFechaTitulo3.WidthRequest = 175;
			this.entFechaTitulo3.Sensitive = false;
			this.entFechaTitulo3.CanFocus = true;
			this.entFechaTitulo3.Name = "entFechaTitulo3";
			this.entFechaTitulo3.IsEditable = true;
			this.entFechaTitulo3.InvisibleChar = '•';
			this.hbox5.Add (this.entFechaTitulo3);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entFechaTitulo3]));
			w33.Position = 4;
			w33.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor2 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor2.WidthRequest = 40;
			this.butCalendarioTituloInstructor2.Sensitive = false;
			this.butCalendarioTituloInstructor2.CanFocus = true;
			this.butCalendarioTituloInstructor2.Name = "butCalendarioTituloInstructor2";
			this.butCalendarioTituloInstructor2.UseUnderline = true;
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor2.Image = w34;
			this.hbox5.Add (this.butCalendarioTituloInstructor2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.butCalendarioTituloInstructor2]));
			w35.Position = 5;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butEliminarProfesion3 = new global::Gtk.Button ();
			this.butEliminarProfesion3.WidthRequest = 40;
			this.butEliminarProfesion3.Sensitive = false;
			this.butEliminarProfesion3.CanFocus = true;
			this.butEliminarProfesion3.Name = "butEliminarProfesion3";
			this.butEliminarProfesion3.UseUnderline = true;
			global::Gtk.Image w36 = new global::Gtk.Image ();
			w36.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion3.Image = w36;
			this.hbox5.Add (this.butEliminarProfesion3);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.butEliminarProfesion3]));
			w37.Position = 6;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.butAgregarProfesion4 = new global::Gtk.Button ();
			this.butAgregarProfesion4.WidthRequest = 40;
			this.butAgregarProfesion4.Sensitive = false;
			this.butAgregarProfesion4.CanFocus = true;
			this.butAgregarProfesion4.Name = "butAgregarProfesion4";
			this.butAgregarProfesion4.UseUnderline = true;
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion4.Image = w39;
			this.hbox6.Add (this.butAgregarProfesion4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.butAgregarProfesion4]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labProfesión4 = new global::Gtk.Label ();
			this.labProfesión4.WidthRequest = 100;
			this.labProfesión4.HeightRequest = 35;
			this.labProfesión4.Sensitive = false;
			this.labProfesión4.Name = "labProfesión4";
			this.labProfesión4.Xalign = 0F;
			this.labProfesión4.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox6.Add (this.labProfesión4);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.labProfesión4]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Padding = ((uint)(10));
			// Container child hbox6.Gtk.Box+BoxChild
			this.cbboxProfesion4 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion4.WidthRequest = 200;
			this.cbboxProfesion4.Sensitive = false;
			this.cbboxProfesion4.Name = "cbboxProfesion4";
			this.hbox6.Add (this.cbboxProfesion4);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.cbboxProfesion4]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labFechaTitulo3 = new global::Gtk.Label ();
			this.labFechaTitulo3.WidthRequest = 130;
			this.labFechaTitulo3.HeightRequest = 35;
			this.labFechaTitulo3.Sensitive = false;
			this.labFechaTitulo3.Name = "labFechaTitulo3";
			this.labFechaTitulo3.Xalign = 0F;
			this.labFechaTitulo3.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox6.Add (this.labFechaTitulo3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.labFechaTitulo3]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Padding = ((uint)(10));
			// Container child hbox6.Gtk.Box+BoxChild
			this.entFechaTitulo4 = new global::Gtk.Entry ();
			this.entFechaTitulo4.WidthRequest = 175;
			this.entFechaTitulo4.Sensitive = false;
			this.entFechaTitulo4.CanFocus = true;
			this.entFechaTitulo4.Name = "entFechaTitulo4";
			this.entFechaTitulo4.IsEditable = true;
			this.entFechaTitulo4.InvisibleChar = '•';
			this.hbox6.Add (this.entFechaTitulo4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entFechaTitulo4]));
			w44.Position = 4;
			w44.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor3 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor3.WidthRequest = 40;
			this.butCalendarioTituloInstructor3.Sensitive = false;
			this.butCalendarioTituloInstructor3.CanFocus = true;
			this.butCalendarioTituloInstructor3.Name = "butCalendarioTituloInstructor3";
			this.butCalendarioTituloInstructor3.UseUnderline = true;
			global::Gtk.Image w45 = new global::Gtk.Image ();
			w45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor3.Image = w45;
			this.hbox6.Add (this.butCalendarioTituloInstructor3);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.butCalendarioTituloInstructor3]));
			w46.Position = 5;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.butEliminarProfesion4 = new global::Gtk.Button ();
			this.butEliminarProfesion4.WidthRequest = 40;
			this.butEliminarProfesion4.Sensitive = false;
			this.butEliminarProfesion4.CanFocus = true;
			this.butEliminarProfesion4.Name = "butEliminarProfesion4";
			this.butEliminarProfesion4.UseUnderline = true;
			global::Gtk.Image w47 = new global::Gtk.Image ();
			w47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion4.Image = w47;
			this.hbox6.Add (this.butEliminarProfesion4);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.butEliminarProfesion4]));
			w48.Position = 6;
			w48.Expand = false;
			w48.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w49.Position = 4;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.butAgregarProfesion5 = new global::Gtk.Button ();
			this.butAgregarProfesion5.WidthRequest = 40;
			this.butAgregarProfesion5.Sensitive = false;
			this.butAgregarProfesion5.CanFocus = true;
			this.butAgregarProfesion5.Name = "butAgregarProfesion5";
			this.butAgregarProfesion5.UseUnderline = true;
			global::Gtk.Image w50 = new global::Gtk.Image ();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion5.Image = w50;
			this.hbox7.Add (this.butAgregarProfesion5);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.butAgregarProfesion5]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labProfesión5 = new global::Gtk.Label ();
			this.labProfesión5.WidthRequest = 100;
			this.labProfesión5.HeightRequest = 35;
			this.labProfesión5.Sensitive = false;
			this.labProfesión5.Name = "labProfesión5";
			this.labProfesión5.Xalign = 0F;
			this.labProfesión5.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox7.Add (this.labProfesión5);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labProfesión5]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Padding = ((uint)(10));
			// Container child hbox7.Gtk.Box+BoxChild
			this.cbboxProfesion5 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion5.WidthRequest = 200;
			this.cbboxProfesion5.Sensitive = false;
			this.cbboxProfesion5.Name = "cbboxProfesion5";
			this.hbox7.Add (this.cbboxProfesion5);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.cbboxProfesion5]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labFechaTitulo4 = new global::Gtk.Label ();
			this.labFechaTitulo4.WidthRequest = 130;
			this.labFechaTitulo4.HeightRequest = 35;
			this.labFechaTitulo4.Sensitive = false;
			this.labFechaTitulo4.Name = "labFechaTitulo4";
			this.labFechaTitulo4.Xalign = 0F;
			this.labFechaTitulo4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox7.Add (this.labFechaTitulo4);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labFechaTitulo4]));
			w54.Position = 3;
			w54.Expand = false;
			w54.Padding = ((uint)(10));
			// Container child hbox7.Gtk.Box+BoxChild
			this.entFechaTitulo5 = new global::Gtk.Entry ();
			this.entFechaTitulo5.WidthRequest = 175;
			this.entFechaTitulo5.Sensitive = false;
			this.entFechaTitulo5.CanFocus = true;
			this.entFechaTitulo5.Name = "entFechaTitulo5";
			this.entFechaTitulo5.IsEditable = true;
			this.entFechaTitulo5.InvisibleChar = '•';
			this.hbox7.Add (this.entFechaTitulo5);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entFechaTitulo5]));
			w55.Position = 4;
			w55.Expand = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor4 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor4.WidthRequest = 40;
			this.butCalendarioTituloInstructor4.Sensitive = false;
			this.butCalendarioTituloInstructor4.CanFocus = true;
			this.butCalendarioTituloInstructor4.Name = "butCalendarioTituloInstructor4";
			this.butCalendarioTituloInstructor4.UseUnderline = true;
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor4.Image = w56;
			this.hbox7.Add (this.butCalendarioTituloInstructor4);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.butCalendarioTituloInstructor4]));
			w57.Position = 5;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.butEliminarProfesion5 = new global::Gtk.Button ();
			this.butEliminarProfesion5.WidthRequest = 40;
			this.butEliminarProfesion5.Sensitive = false;
			this.butEliminarProfesion5.CanFocus = true;
			this.butEliminarProfesion5.Name = "butEliminarProfesion5";
			this.butEliminarProfesion5.UseUnderline = true;
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion5.Image = w58;
			this.hbox7.Add (this.butEliminarProfesion5);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.butEliminarProfesion5]));
			w59.Position = 6;
			w59.Expand = false;
			w59.Fill = false;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w60.Position = 5;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.butAgregarProfesion6 = new global::Gtk.Button ();
			this.butAgregarProfesion6.WidthRequest = 40;
			this.butAgregarProfesion6.Sensitive = false;
			this.butAgregarProfesion6.CanFocus = true;
			this.butAgregarProfesion6.Name = "butAgregarProfesion6";
			this.butAgregarProfesion6.UseUnderline = true;
			global::Gtk.Image w61 = new global::Gtk.Image ();
			w61.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion6.Image = w61;
			this.hbox8.Add (this.butAgregarProfesion6);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.butAgregarProfesion6]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labProfesión6 = new global::Gtk.Label ();
			this.labProfesión6.WidthRequest = 100;
			this.labProfesión6.HeightRequest = 35;
			this.labProfesión6.Sensitive = false;
			this.labProfesión6.Name = "labProfesión6";
			this.labProfesión6.Xalign = 0F;
			this.labProfesión6.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox8.Add (this.labProfesión6);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.labProfesión6]));
			w63.Position = 1;
			w63.Expand = false;
			w63.Padding = ((uint)(10));
			// Container child hbox8.Gtk.Box+BoxChild
			this.cbboxProfesion6 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion6.WidthRequest = 200;
			this.cbboxProfesion6.Sensitive = false;
			this.cbboxProfesion6.Name = "cbboxProfesion6";
			this.hbox8.Add (this.cbboxProfesion6);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.cbboxProfesion6]));
			w64.Position = 2;
			w64.Expand = false;
			w64.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labFechaTitulo5 = new global::Gtk.Label ();
			this.labFechaTitulo5.WidthRequest = 130;
			this.labFechaTitulo5.HeightRequest = 35;
			this.labFechaTitulo5.Sensitive = false;
			this.labFechaTitulo5.Name = "labFechaTitulo5";
			this.labFechaTitulo5.Xalign = 0F;
			this.labFechaTitulo5.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox8.Add (this.labFechaTitulo5);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.labFechaTitulo5]));
			w65.Position = 3;
			w65.Expand = false;
			w65.Padding = ((uint)(10));
			// Container child hbox8.Gtk.Box+BoxChild
			this.entFechaTitulo6 = new global::Gtk.Entry ();
			this.entFechaTitulo6.WidthRequest = 175;
			this.entFechaTitulo6.Sensitive = false;
			this.entFechaTitulo6.CanFocus = true;
			this.entFechaTitulo6.Name = "entFechaTitulo6";
			this.entFechaTitulo6.IsEditable = true;
			this.entFechaTitulo6.InvisibleChar = '•';
			this.hbox8.Add (this.entFechaTitulo6);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entFechaTitulo6]));
			w66.Position = 4;
			w66.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor5 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor5.WidthRequest = 40;
			this.butCalendarioTituloInstructor5.Sensitive = false;
			this.butCalendarioTituloInstructor5.CanFocus = true;
			this.butCalendarioTituloInstructor5.Name = "butCalendarioTituloInstructor5";
			this.butCalendarioTituloInstructor5.UseUnderline = true;
			global::Gtk.Image w67 = new global::Gtk.Image ();
			w67.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor5.Image = w67;
			this.hbox8.Add (this.butCalendarioTituloInstructor5);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.butCalendarioTituloInstructor5]));
			w68.Position = 5;
			w68.Expand = false;
			w68.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.butEliminarProfesion6 = new global::Gtk.Button ();
			this.butEliminarProfesion6.WidthRequest = 40;
			this.butEliminarProfesion6.Sensitive = false;
			this.butEliminarProfesion6.CanFocus = true;
			this.butEliminarProfesion6.Name = "butEliminarProfesion6";
			this.butEliminarProfesion6.UseUnderline = true;
			global::Gtk.Image w69 = new global::Gtk.Image ();
			w69.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion6.Image = w69;
			this.hbox8.Add (this.butEliminarProfesion6);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.butEliminarProfesion6]));
			w70.Position = 6;
			w70.Expand = false;
			w70.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w71.Position = 6;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.butAgregarProfesion7 = new global::Gtk.Button ();
			this.butAgregarProfesion7.WidthRequest = 40;
			this.butAgregarProfesion7.Sensitive = false;
			this.butAgregarProfesion7.CanFocus = true;
			this.butAgregarProfesion7.Name = "butAgregarProfesion7";
			this.butAgregarProfesion7.UseUnderline = true;
			global::Gtk.Image w72 = new global::Gtk.Image ();
			w72.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion7.Image = w72;
			this.hbox9.Add (this.butAgregarProfesion7);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.butAgregarProfesion7]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.labProfesión7 = new global::Gtk.Label ();
			this.labProfesión7.WidthRequest = 100;
			this.labProfesión7.HeightRequest = 35;
			this.labProfesión7.Sensitive = false;
			this.labProfesión7.Name = "labProfesión7";
			this.labProfesión7.Xalign = 0F;
			this.labProfesión7.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox9.Add (this.labProfesión7);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.labProfesión7]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Padding = ((uint)(10));
			// Container child hbox9.Gtk.Box+BoxChild
			this.cbboxProfesion7 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion7.WidthRequest = 200;
			this.cbboxProfesion7.Sensitive = false;
			this.cbboxProfesion7.Name = "cbboxProfesion7";
			this.hbox9.Add (this.cbboxProfesion7);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.cbboxProfesion7]));
			w75.Position = 2;
			w75.Expand = false;
			w75.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.labFechaTitulo6 = new global::Gtk.Label ();
			this.labFechaTitulo6.WidthRequest = 130;
			this.labFechaTitulo6.HeightRequest = 35;
			this.labFechaTitulo6.Sensitive = false;
			this.labFechaTitulo6.Name = "labFechaTitulo6";
			this.labFechaTitulo6.Xalign = 0F;
			this.labFechaTitulo6.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox9.Add (this.labFechaTitulo6);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.labFechaTitulo6]));
			w76.Position = 3;
			w76.Expand = false;
			w76.Padding = ((uint)(10));
			// Container child hbox9.Gtk.Box+BoxChild
			this.entFechaTitulo7 = new global::Gtk.Entry ();
			this.entFechaTitulo7.WidthRequest = 175;
			this.entFechaTitulo7.Sensitive = false;
			this.entFechaTitulo7.CanFocus = true;
			this.entFechaTitulo7.Name = "entFechaTitulo7";
			this.entFechaTitulo7.IsEditable = true;
			this.entFechaTitulo7.InvisibleChar = '•';
			this.hbox9.Add (this.entFechaTitulo7);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entFechaTitulo7]));
			w77.Position = 4;
			w77.Expand = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor6 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor6.WidthRequest = 40;
			this.butCalendarioTituloInstructor6.Sensitive = false;
			this.butCalendarioTituloInstructor6.CanFocus = true;
			this.butCalendarioTituloInstructor6.Name = "butCalendarioTituloInstructor6";
			this.butCalendarioTituloInstructor6.UseUnderline = true;
			global::Gtk.Image w78 = new global::Gtk.Image ();
			w78.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor6.Image = w78;
			this.hbox9.Add (this.butCalendarioTituloInstructor6);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.butCalendarioTituloInstructor6]));
			w79.Position = 5;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.butEliminarProfesion7 = new global::Gtk.Button ();
			this.butEliminarProfesion7.WidthRequest = 40;
			this.butEliminarProfesion7.Sensitive = false;
			this.butEliminarProfesion7.CanFocus = true;
			this.butEliminarProfesion7.Name = "butEliminarProfesion7";
			this.butEliminarProfesion7.UseUnderline = true;
			global::Gtk.Image w80 = new global::Gtk.Image ();
			w80.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion7.Image = w80;
			this.hbox9.Add (this.butEliminarProfesion7);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.butEliminarProfesion7]));
			w81.Position = 6;
			w81.Expand = false;
			w81.Fill = false;
			this.vbox1.Add (this.hbox9);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
			w82.Position = 7;
			w82.Expand = false;
			w82.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.butAgregarProfesion8 = new global::Gtk.Button ();
			this.butAgregarProfesion8.WidthRequest = 40;
			this.butAgregarProfesion8.Sensitive = false;
			this.butAgregarProfesion8.CanFocus = true;
			this.butAgregarProfesion8.Name = "butAgregarProfesion8";
			this.butAgregarProfesion8.UseUnderline = true;
			global::Gtk.Image w83 = new global::Gtk.Image ();
			w83.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.butAgregarProfesion8.Image = w83;
			this.hbox10.Add (this.butAgregarProfesion8);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.butAgregarProfesion8]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.labProfesión8 = new global::Gtk.Label ();
			this.labProfesión8.WidthRequest = 100;
			this.labProfesión8.HeightRequest = 35;
			this.labProfesión8.Sensitive = false;
			this.labProfesión8.Name = "labProfesión8";
			this.labProfesión8.Xalign = 0F;
			this.labProfesión8.LabelProp = global::Mono.Unix.Catalog.GetString ("Profesión: ");
			this.hbox10.Add (this.labProfesión8);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.labProfesión8]));
			w85.Position = 1;
			w85.Expand = false;
			w85.Padding = ((uint)(10));
			// Container child hbox10.Gtk.Box+BoxChild
			this.cbboxProfesion8 = global::Gtk.ComboBox.NewText ();
			this.cbboxProfesion8.WidthRequest = 200;
			this.cbboxProfesion8.Sensitive = false;
			this.cbboxProfesion8.Name = "cbboxProfesion8";
			this.hbox10.Add (this.cbboxProfesion8);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.cbboxProfesion8]));
			w86.Position = 2;
			w86.Expand = false;
			w86.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.labFechaTitulo7 = new global::Gtk.Label ();
			this.labFechaTitulo7.WidthRequest = 130;
			this.labFechaTitulo7.HeightRequest = 35;
			this.labFechaTitulo7.Sensitive = false;
			this.labFechaTitulo7.Name = "labFechaTitulo7";
			this.labFechaTitulo7.Xalign = 0F;
			this.labFechaTitulo7.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha del Título: ");
			this.hbox10.Add (this.labFechaTitulo7);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.labFechaTitulo7]));
			w87.Position = 3;
			w87.Expand = false;
			w87.Padding = ((uint)(10));
			// Container child hbox10.Gtk.Box+BoxChild
			this.entFechaTitulo8 = new global::Gtk.Entry ();
			this.entFechaTitulo8.WidthRequest = 175;
			this.entFechaTitulo8.Sensitive = false;
			this.entFechaTitulo8.CanFocus = true;
			this.entFechaTitulo8.Name = "entFechaTitulo8";
			this.entFechaTitulo8.IsEditable = true;
			this.entFechaTitulo8.InvisibleChar = '•';
			this.hbox10.Add (this.entFechaTitulo8);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.entFechaTitulo8]));
			w88.Position = 4;
			w88.Expand = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.butCalendarioTituloInstructor7 = new global::Gtk.Button ();
			this.butCalendarioTituloInstructor7.WidthRequest = 40;
			this.butCalendarioTituloInstructor7.Sensitive = false;
			this.butCalendarioTituloInstructor7.CanFocus = true;
			this.butCalendarioTituloInstructor7.Name = "butCalendarioTituloInstructor7";
			this.butCalendarioTituloInstructor7.UseUnderline = true;
			global::Gtk.Image w89 = new global::Gtk.Image ();
			w89.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.butCalendarioTituloInstructor7.Image = w89;
			this.hbox10.Add (this.butCalendarioTituloInstructor7);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.butCalendarioTituloInstructor7]));
			w90.Position = 5;
			w90.Expand = false;
			w90.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.butEliminarProfesion8 = new global::Gtk.Button ();
			this.butEliminarProfesion8.WidthRequest = 40;
			this.butEliminarProfesion8.Sensitive = false;
			this.butEliminarProfesion8.CanFocus = true;
			this.butEliminarProfesion8.Name = "butEliminarProfesion8";
			this.butEliminarProfesion8.UseUnderline = true;
			global::Gtk.Image w91 = new global::Gtk.Image ();
			w91.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_stop", global::Gtk.IconSize.Menu);
			this.butEliminarProfesion8.Image = w91;
			this.hbox10.Add (this.butEliminarProfesion8);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.butEliminarProfesion8]));
			w92.Position = 6;
			w92.Expand = false;
			w92.Fill = false;
			this.vbox1.Add (this.hbox10);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox10]));
			w93.Position = 8;
			w93.Expand = false;
			w93.Fill = false;
			this.vbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
			w94.Position = 0;
			w94.Expand = false;
			w94.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.butCancelar = new global::Gtk.Button ();
			this.butCancelar.WidthRequest = 50;
			this.butCancelar.HeightRequest = 50;
			this.butCancelar.CanFocus = true;
			this.butCancelar.Name = "butCancelar";
			this.butCancelar.UseUnderline = true;
			this.butCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox12.Add (this.butCancelar);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.butCancelar]));
			w95.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.butAceptar = new global::Gtk.Button ();
			this.butAceptar.CanFocus = true;
			this.butAceptar.Name = "butAceptar";
			this.butAceptar.UseUnderline = true;
			this.butAceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox12.Add (this.butAceptar);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.butAceptar]));
			w96.Position = 1;
			this.vbox2.Add (this.hbox12);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
			w97.Position = 1;
			this.GtkAligInterior.Add (this.vbox2);
			this.frameProfesion.Add (this.GtkAligInterior);
			this.GtkLabProfesiones = new global::Gtk.Label ();
			this.GtkLabProfesiones.Name = "GtkLabProfesiones";
			this.GtkLabProfesiones.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Profesiones</b>");
			this.GtkLabProfesiones.UseMarkup = true;
			this.frameProfesion.LabelWidget = this.GtkLabProfesiones;
			this.Add (this.frameProfesion);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 877;
			this.DefaultHeight = 498;
			this.Show ();
			this.entCodigoInstructor.Changed += new global::System.EventHandler (this.OnEntCodigoInstructorChanged);
			this.butCalendarioTituloInstructor.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructorClicked);
			this.butAgregarProfesion2.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion2Clicked);
			this.butCalendarioTituloInstructor1.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor1Clicked);
			this.butEliminarProfesion2.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion2Clicked);
			this.butAgregarProfesion3.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion3Clicked);
			this.butCalendarioTituloInstructor2.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor2Clicked);
			this.butEliminarProfesion3.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion3Clicked);
			this.butAgregarProfesion4.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion4Clicked);
			this.butCalendarioTituloInstructor3.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor3Clicked);
			this.butEliminarProfesion4.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion4Clicked);
			this.butAgregarProfesion5.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion5Clicked);
			this.butCalendarioTituloInstructor4.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor4Clicked);
			this.butEliminarProfesion5.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion5Clicked);
			this.butAgregarProfesion6.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion6Clicked);
			this.butCalendarioTituloInstructor5.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor5Clicked);
			this.butEliminarProfesion6.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion6Clicked);
			this.butAgregarProfesion7.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion7Clicked);
			this.butCalendarioTituloInstructor6.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor6Clicked);
			this.butEliminarProfesion7.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion7Clicked);
			this.butAgregarProfesion8.Clicked += new global::System.EventHandler (this.OnButAgregarProfesion8Clicked);
			this.butCalendarioTituloInstructor7.Clicked += new global::System.EventHandler (this.OnButCalendarioTituloInstructor7Clicked);
			this.butEliminarProfesion8.Clicked += new global::System.EventHandler (this.OnButEliminarProfesion8Clicked);
			this.butCancelar.Clicked += new global::System.EventHandler (this.OnButCancelarClicked);
			this.butAceptar.Clicked += new global::System.EventHandler (this.OnButAceptarClicked);
		}
	}
}
