
// This file has been generated by the GUI designer. Do not modify.
namespace DamageControl
{
	public partial class Login
	{
		private global::Gtk.Frame frameLogin;
		
		private global::Gtk.Alignment GtkAligInterior;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Fixed fixedLogin;
		
		private global::Gtk.Label labFecha;
		
		private global::Gtk.Image imgLogo2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label labUsuario;
		
		private global::Gtk.Entry entUsuario;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label labContrasena;
		
		private global::Gtk.Entry entContrasena;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.HSeparator hsepLogin1;
		
		private global::Gtk.CheckButton chButMostrarCont;
		
		private global::Gtk.HSeparator hsepLogin;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button butLimpiar;
		
		private global::Gtk.Button butIniciarSesion;
		
		private global::Gtk.Frame frameRegistrarUsuario;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Expander expRegistro;
		
		private global::Gtk.Alignment alignRegistrar;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button butRegistrar;
		
		private global::Gtk.Image imgNuevoUsuario;
		
		private global::Gtk.Label GtkLabRegistro;
		
		private global::Gtk.Label GtkLalEspacio;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button butSalir;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Label GtkLabBienvenidos;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DamageControl.Login
			this.Name = "DamageControl.Login";
			this.Title = global::Mono.Unix.Catalog.GetString ("Sistema de Entrada");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child DamageControl.Login.Gtk.Container+ContainerChild
			this.frameLogin = new global::Gtk.Frame ();
			this.frameLogin.Name = "frameLogin";
			this.frameLogin.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frameLogin.BorderWidth = ((uint)(15));
			// Container child frameLogin.Gtk.Container+ContainerChild
			this.GtkAligInterior = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAligInterior.Name = "GtkAligInterior";
			this.GtkAligInterior.LeftPadding = ((uint)(12));
			this.GtkAligInterior.BorderWidth = ((uint)(15));
			// Container child GtkAligInterior.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixedLogin = new global::Gtk.Fixed ();
			this.fixedLogin.Name = "fixedLogin";
			this.fixedLogin.HasWindow = false;
			this.hbox4.Add (this.fixedLogin);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixedLogin]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labFecha = new global::Gtk.Label ();
			this.labFecha.WidthRequest = 200;
			this.labFecha.Name = "labFecha";
			this.labFecha.Xalign = 0F;
			this.labFecha.LabelProp = global::Mono.Unix.Catalog.GetString ("labFecha");
			this.hbox4.Add (this.labFecha);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labFecha]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.imgLogo2 = new global::Gtk.Image ();
			this.imgLogo2.Name = "imgLogo2";
			this.imgLogo2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("DamageControl.imagenes.Logo-Damage-Control.png");
			this.vbox1.Add (this.imgLogo2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.imgLogo2]));
			w5.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labUsuario = new global::Gtk.Label ();
			this.labUsuario.WidthRequest = 100;
			this.labUsuario.Name = "labUsuario";
			this.labUsuario.Xalign = 0F;
			this.labUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Usuario: </b>");
			this.labUsuario.UseMarkup = true;
			this.hbox1.Add (this.labUsuario);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labUsuario]));
			w6.Position = 0;
			w6.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entUsuario = new global::Gtk.Entry ();
			this.entUsuario.CanFocus = true;
			this.entUsuario.Name = "entUsuario";
			this.entUsuario.IsEditable = true;
			this.entUsuario.InvisibleChar = '•';
			this.hbox1.Add (this.entUsuario);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entUsuario]));
			w7.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labContrasena = new global::Gtk.Label ();
			this.labContrasena.WidthRequest = 100;
			this.labContrasena.Name = "labContrasena";
			this.labContrasena.Xalign = 0F;
			this.labContrasena.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Contraseña: </b>");
			this.labContrasena.UseMarkup = true;
			this.hbox2.Add (this.labContrasena);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labContrasena]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entContrasena = new global::Gtk.Entry ();
			this.entContrasena.CanFocus = true;
			this.entContrasena.Name = "entContrasena";
			this.entContrasena.IsEditable = true;
			this.entContrasena.Visibility = false;
			this.entContrasena.InvisibleChar = '•';
			this.hbox2.Add (this.entContrasena);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entContrasena]));
			w10.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hsepLogin1 = new global::Gtk.HSeparator ();
			this.hsepLogin1.Name = "hsepLogin1";
			this.hbox7.Add (this.hsepLogin1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hsepLogin1]));
			w12.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.chButMostrarCont = new global::Gtk.CheckButton ();
			this.chButMostrarCont.CanFocus = true;
			this.chButMostrarCont.Name = "chButMostrarCont";
			this.chButMostrarCont.Label = global::Mono.Unix.Catalog.GetString ("Mostrar contraseña");
			this.chButMostrarCont.DrawIndicator = true;
			this.chButMostrarCont.UseUnderline = true;
			this.chButMostrarCont.BorderWidth = ((uint)(6));
			this.hbox7.Add (this.chButMostrarCont);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.chButMostrarCont]));
			w13.Position = 1;
			w13.Expand = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hsepLogin = new global::Gtk.HSeparator ();
			this.hsepLogin.Name = "hsepLogin";
			this.hbox7.Add (this.hsepLogin);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hsepLogin]));
			w14.Position = 2;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.butLimpiar = new global::Gtk.Button ();
			this.butLimpiar.HeightRequest = 50;
			this.butLimpiar.CanFocus = true;
			this.butLimpiar.Name = "butLimpiar";
			this.butLimpiar.UseUnderline = true;
			this.butLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox3.Add (this.butLimpiar);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.butLimpiar]));
			w16.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.butIniciarSesion = new global::Gtk.Button ();
			this.butIniciarSesion.HeightRequest = 50;
			this.butIniciarSesion.CanFocus = true;
			this.butIniciarSesion.Events = ((global::Gdk.EventMask)(1024));
			this.butIniciarSesion.Name = "butIniciarSesion";
			this.butIniciarSesion.UseUnderline = true;
			this.butIniciarSesion.Label = global::Mono.Unix.Catalog.GetString ("Iniciar sesión");
			this.hbox3.Add (this.butIniciarSesion);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.butIniciarSesion]));
			w17.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w18.Position = 6;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameRegistrarUsuario = new global::Gtk.Frame ();
			this.frameRegistrarUsuario.Name = "frameRegistrarUsuario";
			this.frameRegistrarUsuario.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameRegistrarUsuario.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.expRegistro = new global::Gtk.Expander (null);
			this.expRegistro.CanFocus = true;
			this.expRegistro.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.expRegistro.Name = "expRegistro";
			this.expRegistro.Expanded = true;
			this.expRegistro.BorderWidth = ((uint)(9));
			// Container child expRegistro.Gtk.Container+ContainerChild
			this.alignRegistrar = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignRegistrar.Name = "alignRegistrar";
			this.alignRegistrar.BorderWidth = ((uint)(10));
			// Container child alignRegistrar.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.butRegistrar = new global::Gtk.Button ();
			this.butRegistrar.HeightRequest = 50;
			this.butRegistrar.CanFocus = true;
			this.butRegistrar.Name = "butRegistrar";
			this.butRegistrar.UseUnderline = true;
			this.butRegistrar.Label = global::Mono.Unix.Catalog.GetString ("¡Únetenos!");
			this.hbox6.Add (this.butRegistrar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.butRegistrar]));
			w19.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.imgNuevoUsuario = new global::Gtk.Image ();
			this.imgNuevoUsuario.Name = "imgNuevoUsuario";
			this.imgNuevoUsuario.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("DamageControl.imagenes.RegistrarUsuario.png");
			this.hbox6.Add (this.imgNuevoUsuario);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.imgNuevoUsuario]));
			w20.Position = 1;
			this.alignRegistrar.Add (this.hbox6);
			this.expRegistro.Add (this.alignRegistrar);
			this.GtkLabRegistro = new global::Gtk.Label ();
			this.GtkLabRegistro.Name = "GtkLabRegistro";
			this.GtkLabRegistro.LabelProp = global::Mono.Unix.Catalog.GetString ("¿No tienes cuenta? ¡Registrate!");
			this.GtkLabRegistro.UseMarkup = true;
			this.GtkLabRegistro.UseUnderline = true;
			this.expRegistro.LabelWidget = this.GtkLabRegistro;
			this.GtkAlignment.Add (this.expRegistro);
			this.frameRegistrarUsuario.Add (this.GtkAlignment);
			this.GtkLalEspacio = new global::Gtk.Label ();
			this.GtkLalEspacio.Name = "GtkLalEspacio";
			this.GtkLalEspacio.LabelProp = global::Mono.Unix.Catalog.GetString ("<b></b>");
			this.GtkLalEspacio.UseMarkup = true;
			this.frameRegistrarUsuario.LabelWidget = this.GtkLalEspacio;
			this.vbox1.Add (this.frameRegistrarUsuario);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameRegistrarUsuario]));
			w25.Position = 7;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox5.Add (this.fixed2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed2]));
			w26.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butSalir = new global::Gtk.Button ();
			this.butSalir.HeightRequest = 50;
			this.butSalir.CanFocus = true;
			this.butSalir.Name = "butSalir";
			this.butSalir.UseUnderline = true;
			this.butSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir del Sistema");
			this.hbox5.Add (this.butSalir);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.butSalir]));
			w27.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox5.Add (this.fixed3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed3]));
			w28.Position = 2;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w29.Position = 8;
			w29.Expand = false;
			w29.Fill = false;
			this.GtkAligInterior.Add (this.vbox1);
			this.frameLogin.Add (this.GtkAligInterior);
			this.GtkLabBienvenidos = new global::Gtk.Label ();
			this.GtkLabBienvenidos.Name = "GtkLabBienvenidos";
			this.GtkLabBienvenidos.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>¡Bienvenido!</b>");
			this.GtkLabBienvenidos.UseMarkup = true;
			this.frameLogin.LabelWidget = this.GtkLabBienvenidos;
			this.Add (this.frameLogin);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 512;
			this.DefaultHeight = 647;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.entUsuario.Changed += new global::System.EventHandler (this.OnEntUsuarioChanged);
			this.chButMostrarCont.Clicked += new global::System.EventHandler (this.OnChButMostrarContClicked);
			this.butLimpiar.Clicked += new global::System.EventHandler (this.OnButLimpiarClicked);
			this.butIniciarSesion.Clicked += new global::System.EventHandler (this.OnButIniciarSesionClicked);
			this.expRegistro.Activated += new global::System.EventHandler (this.OnExpRegistroActivated);
			this.butRegistrar.Clicked += new global::System.EventHandler (this.OnButRegistrarClicked);
			this.butSalir.Clicked += new global::System.EventHandler (this.OnButSalirClicked);
		}
	}
}
